repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: 
          - --py39-plus
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=google
          - --skip-glob=wandb/**/*
          - --thirdparty=wandb
  - repo: https://github.com/myint/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        args:
          - -r
          - --exclude=wandb, __init__.py
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args:
          - --style=yapf
          - --in-place
          - --recursive
          - --exclude=wandb, __init__.py
  # - repo: https://github.com/python/black
  #   rev: 23.1.0
  #   hooks:
  #     - id: black
  #       args:
  #         - --line-length=120
  #         - --exclude=wandb, __init__.py
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - -L=complies
